version: '3'

services:
  ordersdb:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=luzma
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=ordersdatabase

